---
resources:
- name: pal-tracker
  type: git
  source:
    uri: git@github.com:pivotal-izabela-gomes/pal-tracker-icg.git
    branch: master
    private_key: {{github-private-key}}

- name: deploy
  type: cf
  source:
    api: https://api.sys.quandary.pal.pivotal.io
    username: {{deploy-username}}
    password: {{deploy-password}}
    organization: {{deploy-org}}
    space: {{deploy-space}}
    skip_cert_check: true

jobs:
- name: build-and-deploy
  plan:
  - get: pal-tracker
    trigger: true
  - task: build
    file: pal-tracker/ci/tasks/build.yml
  - put: deploy
    params:
      WELCOME_MESSAGE: "Hello from Concourse"
